development:
  adapter: mysql2
  encoding: utf8
  database: dev_listingsmgr_app
  username: root
  password: Palo5non!
test:
  adapter: mysql2
  database: test_listingsmgr_app
  username: root
  password: Palo5non!
production:
  adapter: mysql2
  encoding: utf8
  database: sch_listingsmgr mydb
  username: root
  password: Palo5non!